### ISSUE TITLE
No page 2 for the blog?

### ISSUE THREAD

**Issue by JohnRMoreau** [swcarpentry/training-course#175]
Whenever I try to go to page 2 of the training course blog, I get a 404 error. Not sure where the error might be.

**Comment by gvwilson** [comment]
What page are you on and what link are you clicking to produce this error?

**Comment by JohnRMoreau** [comment]
I think I actually have two errors:
1. ```
     The page 2 error
   ```
- ```
      I’m starting from http://swcarpentry.github.io/training-course/2015/02/second-meeting/
  ```
- ```
      Then I click on the blog link at the top of the screen, which takes me to http://swcarpentry.github.io/training-course/blog/
  ```
- ```
      From there, I navigate to the bottom of the page and click the link for next which should lead to http://swcarpentry.github.io/blog/page2/
  ```

But instead takes me to a 404 error page.
1. ```
     Round 12 material not on the blog 
   ```
- ```
      I’m starting from http://swcarpentry.github.io/training-course/2015/02/second-meeting/
  ```
- ```
      Then I click on the blog link at the top of the screen, which takes me to http://swcarpentry.github.io/training-course/blog/
  ```
- ```
      This page does not have any 2015 content on it. The last update was your (Greg’s) post on a well-written lesson plan from November 6th, 2014.
  ```
- ```
      The only way I can get at our cohort’s posts is through the Round 12 link on the left. That takes me to a list of student posts as well as your posts. 
  ```

Since I’m new to this site, let me ask: how should the site work? It could be that a choice was made not to publish the posts from a round until after the round concludes. If so, the site is behaving as expected with regards to the Round 12 posts. If not, we may have a problem. Either way, the page 2  behavior is more likely to be an error. For what it’s worth, I’ve had these errors on multiple machines and browsers. 

I hope the above isn’t overkill. I’m in the middle of data documentation at work, so I’ve been doing a lot of detailed technical descriptions. 

From: Greg Wilson [mailto:notifications@github.com] 
Sent: Sunday, February 22, 2015 7:41 PM
To: swcarpentry/training-course
Cc: JohnRMoreau
Subject: Re: [training-course] No page 2 for the blog? (#175)

What page are you on and what link are you clicking to produce this error?

—
Reply to this email directly or view it on GitHub https://github.com/swcarpentry/training-course/issues/175#issuecomment-75478792 .  https://github.com/notifications/beacon/AEGUnuCT7iJe4CVzOT4KQyKDbNRLA5Joks5nunyRgaJpZM4DkC-A.gif 

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by gvwilson** [comment]
Ah hah - the 'blog' link is going to posts that aren't part of any 
particular round.  That, I can fix :-)
Cheers,
Greg

On 2015-02-24 1:23 PM, JohnRMoreau wrote:

> I think I actually have two errors:
> 1. The page 2 error
> - I’m starting from 
>   http://swcarpentry.github.io/training-course/2015/02/second-meeting/
> - Then I click on the blog link at the top of the screen, which takes 
>   me to http://swcarpentry.github.io/training-course/blog/
> - From there, I navigate to the bottom of the page and click the link 
>   for next which should lead to http://swcarpentry.github.io/blog/page2/
> 
> But instead takes me to a 404 error page.
> 1. Round 12 material not on the blog
> - I’m starting from 
>   http://swcarpentry.github.io/training-course/2015/02/second-meeting/
> - Then I click on the blog link at the top of the screen, which takes 
>   me to http://swcarpentry.github.io/training-course/blog/
> - This page does not have any 2015 content on it. The last update was 
>   your (Greg’s) post on a well-written lesson plan from November 6th, 2014.
> - The only way I can get at our cohort’s posts is through the Round 12 
>   link on the left. That takes me to a list of student posts as well as 
>   your posts.
> 
> Since I’m new to this site, let me ask: how should the site work? It 
> could be that a choice was made not to publish the posts from a round 
> until after the round concludes. If so, the site is behaving as 
> expected with regards to the Round 12 posts. If not, we may have a 
> problem. Either way, the page 2 behavior is more likely to be an 
> error. For what it’s worth, I’ve had these errors on multiple machines 
> and browsers.
> 
> I hope the above isn’t overkill. I’m in the middle of data 
> documentation at work, so I’ve been doing a lot of detailed technical 
> descriptions.
> 
> From: Greg Wilson [mailto:notifications@github.com]
> Sent: Sunday, February 22, 2015 7:41 PM
> To: swcarpentry/training-course
> Cc: JohnRMoreau
> Subject: Re: [training-course] No page 2 for the blog? (#175)
> 
> What page are you on and what link are you clicking to produce this error?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/issues/175#issuecomment-75478792 
> . 
> https://github.com/notifications/beacon/AEGUnuCT7iJe4CVzOT4KQyKDbNRLA5Joks5nunyRgaJpZM4DkC-A.gif 
> 
> ---
> 
> This email has been checked for viruses by Avast antivirus software.
> http://www.avast.com
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/issues/175#issuecomment-75814460.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
