### ISSUE TITLE
Please add a link to the live website

### ISSUE THREAD

**Issue by snim2** [swcarpentry/training-course#304]
In the Git Hub web interface just below the name of the repository there is a description that reads **Instructor training course**. Anyone with collaborator access should see a button called **Edit** which can be used to edit the description and add a link to a website.

It would be super convenient to have a link to the front page of the live site  http://swcarpentry.github.io/training-course/ but unfortunately this bit of Git Hub configuration cannot be changed via a pull request, so I cannot offer to make the change myself :-1: 

Many thanks!

**Comment by gvwilson** [comment]
Done!

**Comment by snim2** [comment]
Ace! Many thanks :+1:
