### ISSUE TITLE
Display number of discussion items alongside list of blog posts

### ISSUE THREAD

**Issue by wd15** [swcarpentry/training-course#372]
With a small amount of client side Javascript it may be possible to display the number of comments for each post in [the blog](http://swcarpentry.github.io/training-course/submissions/round-12/index.html) in a fourth column. This is useful so that those commenting can easily check that every post has at least some comments. In the current state it is very easy for posts to be forgotten about. Maybe also have a separate page that only lists blog posts without any discussion.

**Comment by gvwilson** [comment]
+1 - if you can write the Javascript, we'd be happy to add it.
Thanks,
Greg

**Comment by wd15** [comment]
@gvwilson, sure, I'll assign this to myself when/if I can scope it and feel like it's possible.

**Comment by gvwilson** [comment]
We've completely rebuilt the website since this was filed - see https://github.com/swcarpentry/website, and please re-file there if you're still interested.
