### ISSUE TITLE
Weird problem with Disqus due HTTPS

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/training-course#384]
Someone asked me for help since s/he didn't get the comments.
## Chromium 41.0.2272.89 (64-bit)

If I open http://swcarpentry.github.io/training-course/2015/03/jeremy-gray/ I got

![http](https://cloud.githubusercontent.com/assets/1506457/6784455/8d2b5f90-d15e-11e4-9af7-bfff5f5f76c5.jpg)

If I go to the same address **but this time using HTTPS**, i.e. https://swcarpentry.github.io/training-course/2015/03/jeremy-gray/, I got

![bug](https://cloud.githubusercontent.com/assets/1506457/6784487/c14c5112-d15e-11e4-8c4d-c5f942417dde.jpg)

For unknown reason if I go to https://swcarpentry.github.io/training-course/2015/03/amy-boyle-mcq/, **using HTTPS**, I can see the comments:

![works](https://cloud.githubusercontent.com/assets/1506457/6784448/7d8f0a82-d15e-11e4-8960-e2d3046c5221.jpg)
## Firefox 36.0.4

Similar behavior.
## Firefox Nightly 39.0a1 (2015-03-08)

Similar behavior.

**Comment by rgaiacs** [comment]
@gvwilson Probably this happens because of we will need to **force** load disqus with HTTPS for everyone using

```
dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js?https';
```

as suggested at https://help.disqus.com/customer/portal/articles/542119-can-disqus-be-loaded-via-https-.

**Comment by jeremycg** [comment]
I don't know if this helps, but going to the example https://swcarpentry.github.io/training-course/2015/03/amy-boyle-mcq/ I can see one comment, and the non-https I can see three (different) comments - http://swcarpentry.github.io/training-course/2015/03/amy-boyle-mcq/

My hypothesis is disqus is treating the https and http versions as different entries and keeping the comments seperate.
